### ISSUE TITLE
Wrong AVX rounding mode reported for an instruction

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#642] opened 2016-04-19 21:22 UTC
Compiling this instruction in fasm

```
vmulps zmm7{k5}{z},zmm1,zmm4,{ru-sae}
```

I get the following result in Capstone:

```
0010008B   62 F1 74 DD 59 FC 90   vmulps zmm7 {k5} {z}, zmm1, zmm4, {rn-sae}
```

Rounding mode here is reported as to nearest, while original instruction was round upwards.

`objdump` agrees with fasm:

```
0010008B   62 F1 74 DD 59 FC   vmulps zmm7{k5}{z},zmm1,zmm4,{ru-sae}
```

**Comment by aquynh** [comment] 2016-04-20 02:04
confirmed, will see how to fix this. thanks.

**Comment by kabeor** [comment] 2021-12-02 09:37
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-02 09:37 UTC
