### ISSUE TITLE
arm: blx <imm> (thumb2 encoding) registers as invalid on cortex, other badness

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#881] opened 2017-03-27 02:56 UTC
Reference issue: https://github.com/radare/radare2/issues/7133

**Comment by aquynh** [comment] 2017-03-27 04:14
on my machine:

```
$ cstool thumb fff7c0ea
0  fff7c0ea  blx	#0xfffff584
```

so what is wrong?

**Comment by alvarofe** [comment] 2017-03-28 07:57
The issue is when cpu is cortex gives invalid when cortex supports thumb2 encoding. Read the issue more thoroughly where gives you more info.

**Comment by aquynh** [comment] 2017-03-28 08:04
Lets keep it simple, for the record here: how to reproduce this issue in
Capstone (such as with cstool)?

**Comment by alvarofe** [comment] 2017-03-28 09:07
does cstool have the possibility to specify cpu? otherwise create a simple wrapper in C, i don't think I am here to tell you how make this in capstone :P . http://www.capstone-engine.org/lang_c.html

**Comment by radare** [comment] 2017-03-28 09:31
There's no such thing as cpu in capstone, the problem here is that this guy says that this is a thumb2 instruction as plain cortex (MCLASS mode) and results in error, this instruction is only disassembled correctly when not in MCLASS mode with capstone. neither @alvarofe or me should be filling and responding to this issue, its really disgusting to see day after day that nobody reads, tests or reports things properly.

it is clear now? with cstool works because cstool doesn't supports setting the v8 or the mclass bits in the mode.

**Comment by radare** [comment] 2017-03-28 11:53
In addition, using the v8 mode on arm64 breaks the disassembly, what is the V8 mode suposed to do?

**Comment by kabeor** [comment] 2021-12-30 03:47
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-30 03:47 UTC
