### ISSUE TITLE
Xcode error: Use of 'bpf_insn' with tag type that does not match previous declaration

### ISSUE THREAD

**Issue by ccworld1000** [capstone-engine/capstone#1862] opened 2022-03-23 02:12 UTC
env:
macOS 11.6 
x86-64
Xcode 13
capstone-5.0-rc2

do:
compile -> capstone -> static lib
error:
Use of 'bpf_insn' with tag type that does not match previous declaration
Static, dynamic and framework seem to have compilation problems

pic:
<img width="859" alt="Screen Shot 2022-03-23 at 10 06 54 AM" src="https://user-images.githubusercontent.com/22360168/159610243-ed7d60a7-367b-4d40-9d92-79d97ab8d5ac.png">

**Comment by user202729** [comment] 2024-11-01 02:01
Probably duplicate of https://github.com/capstone-engine/capstone/issues/2316 (that one is newer but there are more explanations there, probably this one shows that the issue has been there for several years)

**Comment by Rot127** [comment] 2024-11-01 09:40
Thanks for pointing this out. Will close this one.

**Closed** 2024-11-01 09:40 UTC
