### ISSUE TITLE
Not sure if this is an issue in capstone-m68k or in the way im using the api

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#655] opened 2016-04-28 13:43 UTC
https://github.com/radare/radare2/issues/4631

**Comment by aquynh** [comment] 2016-04-28 13:57
@emoon, do you have any comments?

**Comment by emoon** [comment] 2016-04-28 15:01
Have to look into detail on this one. It's important that the mode has to be 020+ because 68000 has a 24-bit address buss (while 020+ has 32-bit) otherwise the calculation will be wrong.

**Comment by radare** [comment] 2016-04-28 15:20
The problem is that withiut casting the address the higher bit is expanded and results on a negative value or all the higher part filled by ones. So maybe this cast should be done in capstone and not outside

**Comment by emoon** [comment] 2016-04-28 15:40
I will have a look at it.

**Comment by emoon** [comment] 2016-04-28 15:45
I tested this now

```
****************
Platform: M68K
Code: 0x67 0x06
Disasm:
0x800114ee:     beq.b   #$800114f6
        op_count: 1
                operands[0].type: IMM = 0x800114f6
```

This seems to print the correct result unless I'm missing something?

**Comment by blubberdiblub** [comment] 2016-06-15 12:47
The problem is that radare is using a 64 bit address space to do its analysis on.
As such I believe the root of this particular problem doesn't lie in capstone.

M68K is fundamentally a **32 bit only** architecture (where the MC68000 and MC68010 expose only a 24 bit address bus to the outside world - i.e. RAM and peripherals - but internally they're still addressing with 32 bit) and there's no way for it to address 64 bits.

Addressing (with displacements and all other bells and whistles) designed for a 32 bit address bus will show all kinds of unexpected behavior when you apply it to a 64 bit address space as certain assumptions (wrapping around within 32 bits) will fail to hold.
I had a brief look at the radare code and I suspect that it has more problems with this particular problem in other places of its m68k analysis code as well (which are so unlikely to show up for most cases that they were probably not detected yet).

@radare I think there are 2 possible alternatives to fix it in the radare code:

1. Use a 32 bit address space (`uint32_t addr` or `int32_t addr`, respectively, whichever is desired) so it will wrap around properly by itself.
2. Artificially wrap all m68k addresses to the desired range (`0x0 -> 0xFFFFFFFF` or `-0x80000000 -> 0x7FFFFFFF`, respectively, whichever is desired) **everywhere** where they are used.

**Comment by radare** [comment] 2016-08-14 17:58
@blubberdiblub my workaround is this https://github.com/radare/radare2/commit/adc9922c6aceacc0cffa89bc45a20250a5e43e1f seems fine but it shuold probably require more testing

**Comment by emoon** [comment] 2019-03-05 11:44
Should this be closed or is there something more that needs to be fixed on the Capstone side?

**Comment by XVilka** [comment] 2020-07-23 04:06
@trufae @radare @ret2libc is this still an issue? Could this be closed? Do we have a test for this in radare2?

**Comment by kabeor** [comment] 2021-12-02 09:38
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-02 09:38 UTC
