### ISSUE TITLE
strb/ldrb ARM64 instructions inconsistent with other ldr/str instructions

### ISSUE THREAD

**Issue by saurik** [capstone-engine/capstone#863] opened 2017-02-23 01:05 UTC
On ARM64, the strb and ldrb instructions, when using register indirect memory addressing, seem to return as three register operands, instead of two operands where the second is of type memory (with the base and index fields filled in). An example instruction is 0x38286a30, which is "strb w16, [x17, x8]". For most ldr/str instructions, the the second operand is encoded as a memory operand with .mem.index set to the register (I believe unless the instruction is post-increment in which case there is a third operand for the offset). Maybe there is a reason for this difference in the encoding? If this is not intentional and is a mistake, I'd be willing to try to catalog all the instruction encodings that are weird (or even provide a patch).

**Comment by andrewcalvano** [comment] 2017-06-30 16:13
I have run into this issue as well. I believe I have root caused it and can provide a solution.

In the printAliasInstr function in arch/AArch64/AArch64GenAsmWriter.inc, there is a
switch statement on the return value of MCInst_getOpcode(MI). In the various switch cases, there 
are if conditions that check various aspects of the instruction and, if true, supply a templated assembly string to fill in or, if false, return NULL.

The problem comes up when this condition is true and the function does not immediately return NULL. At the bottom of the function is a loop, that fills in the templated assembly string. This loop does not properly handle memory operands.

To fix it I have substituted the following code for the code on lines 12577-12595 in 
arch/AArch64/AArch64GenAsmWriter.inc

This snippet seems to fix it:

```  SStream_concat0(OS, AsmMnem);
  if (*AsmOps) {
    SStream_concat0(OS, "\t");
    for (c = AsmOps; *c; c++) {
      if (*c == '[') {
        SStream_concat0(OS, "[");
        set_mem_access(MI, true);
      }
      else if (*c == ']') {
        SStream_concat0(OS, "]");
        set_mem_access(MI, false);
      }
      else if (*c == '$') {
        c += 1;
        if (*c == (char)0xff) {
          c += 1;
          OpIdx = *c - 1;
          c += 1;
          PrintMethodIdx = *c - 1;
          printCustomAliasOperand(MI, OpIdx, PrintMethodIdx, OS, MRI);
        } else
          printOperand(MI, *c - 1, OS);
      } else {
        SStream_concat(OS, "%c", *c);
      }
    }
  }

**Comment by aquynh** [comment] 2017-06-30 17:01
can you clarify your idea with a pull request?

**Comment by kabeor** [comment] 2021-12-30 03:47
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-30 03:47 UTC
