### ISSUE TITLE
Extra byte taken into instruction size

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#641] opened 2016-04-19 21:20 UTC
Here's what capstone gives me for an instruction in 32-bit mode:

```
0010008B   62 F1 74 DD 59 FC 90   vmulps zmm7 {k5} {z}, zmm1, zmm4, {rn-sae}
```

The `90` byte is actually a NOP, which is a separate instruction from `vmulps`. For comparison, here's what `objdump` gives me (rounding mode is another issue in Capstone):

```
0010008B   62 F1 74 DD 59 FC   vmulps zmm7{k5}{z},zmm1,zmm4,{ru-sae}
```

**Comment by aquynh** [comment] 2016-04-20 02:03
confirmed. will see how to fix this, thanks!

**Comment by kabeor** [comment] 2021-12-02 09:37
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-02 09:37 UTC
