### ISSUE TITLE
wrong dissasembler on code with data reservation (DD, DB...)

### ISSUE THREAD

**Issue by dorkiOld** [capstone-engine/capstone#621] opened 2016-04-04 11:05 UTC
hi there,
been debugging my code for a while, then turned to PE explorer to see what i've missed, turn out that PEexplorer can somehow determine that a piece of code is actually reserved bytes and not opcode to dissembler..

for example for (intel 32bit):
`8b e5 5d c3 8b ff bb 2c 40 20 97 2a 40 20 ab 2a 40 20 ef 2a 40 20 f9 2a 40 20 0d 2b 40 20 03 2b 40 20 e1 2b 40 20 68 2a 40 20 8d 2a 40 20 a1 2a 40 20 b5 2a 40 20 db 2a 40 20 e5 2a 40 20 d7 2b 40 20 bb 2c 40 20 20 0f 01 02 03 04 0f 0f 05 0f 0f 06 0f 07 0f 0f 08 09 0a 0b 0c 0d 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0f 0e cc cc cc cc 55 8b ec`

**Capstone**:
mov esp, ebp
pop ebp
ret 
mov edi, edi
mov ebx, 0x9700402c
sub al, byte ptr [eax]
.....
mov ebx, 0x402c
sgdt    ptr [edx]
add eax, dword ptr [edi + ecx]
syscall 

and ends here... 

**but PE for example gave me:**
 8BE5                           mov esp,ebp
 5D                             pop ebp
 C3                             retn

 8BFF                           Align   4

 BB2C4000                       dd  CASE_00402CE4_PROC0000
 972A4000                       dd  CASE_00402CE4_PROC0001
 AB2A4000                       dd  CASE_00402CE4_PROC0002
 EF2A4000                       dd  CASE_00402CE4_PROC0003
 F92A4000                       dd  CASE_00402CE4_PROC0004
 0D2B4000                       dd  CASE_00402CE4_PROC0005
 032B4000                       dd  CASE_00402CE4_PROC0006
 E12B4000                       dd  CASE_00402CE4_PROC0007
 682A4000                       dd  CASE_00402CE4_PROC0008
 8D2A4000                       dd  CASE_00402CE4_PROC0009
 A12A4000                       dd  CASE_00402CE4_PROC000A
 B52A4000                       dd  CASE_00402CE4_PROC000B
 DB2A4000                       dd  CASE_00402CE4_PROC000C
 E52A4000                       dd  CASE_00402CE4_PROC000D
 D72B4000                       dd  CASE_00402CE4_PROC000E
 BB2C4000                       dd  CASE_00402CE4_PROC0000

 000F010203040F0F050F+          db  00h, 0Fh, 01h, 02h, 03h, 04h, 0Fh, 0Fh, 05h, 0Fh, 0Fh, 06h, 0Fh, 07h, 0Fh, 0Fh
 08090A0B0C0D0F0F0F0F+          db  08h, 09h, 0Ah, 0Bh, 0Ch, 0Dh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh
 0F0F0F0F0F0F0F0F0F0F+          db  0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh
 0F0F0F0F0F0F0F0F0F0F+          db  0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh
 0F0F0F0F0F0F0F0F0F0F+          db  0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh
 0F0F0F0F0F0F0F0F0F0F+          db  0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh
 0F0F0F0F0F0F0F0E               db  0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Fh, 0Eh

 CCCCCCCC                       Align   8

 55                             push    ebp
 8BEC                           mov ebp,esp

any idea ?
thanks !

**Comment by ibabushkin** [comment] 2016-04-04 11:43
The Capstone engine is just disassembling buffers, whereas PE explorer analyzes controlflow to determine what parts of those buffers are actually executed and represents other regions as data.
To get a similar behaviour using Capstone, analyze the instructions you disassemble and look into the SKIPDATA option(s) to, well, skip data. That way you would effectively reimplement the algorithm tools such as PE explorer use.

**Comment by dorki** [comment] 2016-04-04 12:06
hi there thanks for the answer. i've tried SkipData, that doesnt change anything for the above case..

what do u mean by analyze the instructions ? should i keep track of each CALL or usage in memmory location to see if its inside my code ? that seems impossible bassicly since the above example shows that after i've reached a data i cannot trust the code i have.. so its kind of a paradox isnt it ?

**Comment by aquynh** [comment] 2016-04-04 12:09
nothing is wrong with Capstone here, but the problem is that you are not interpreting the data correctly. after that RET instruction can be data, while you are still trying to decode them as instructions.

**Comment by dorki** [comment] 2016-04-04 12:15
i dont understand, how can i find the RET instruction if not by decoding a code block ? how can i only choose to decode each time only until RET instruction is found ?

and even if i can do that, how would i continue, you said that after RET can be data - is there a way of checking that ? in the above example the first couple of lines in the data are looking exactly like opcodes... so how can i tell ?

**Comment by aquynh** [comment] 2016-04-04 12:24
this will be a long road. from the entry point, you need to interpret each instruction, one by one, like how it is executed. to do this, you have to follow branch instructions. discovering hidden code & distinguish code with data is also a big issue. there are many books about this topic.

you can also read code of static analysis tools to see how they deal with what you are trying to do. something as simple as https://github.com/damonws/xenops can be a good start. more tools are available at http://www.capstone-engine.org/showcase.html

**Comment by Nico01** [comment] 2016-04-06 14:51
@dorki once you get the address of the code you want disassemble (let's say a function), you can use _cs_disasm_iter()_ in a while loop, check if the instruction's id is RET and exit if that condition is true.
Something like this https://github.com/Nico01/ded/blob/master/core.c#L442

**Comment by kabeor** [comment] 2021-12-02 09:36
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-02 09:36 UTC
Labels: question
