### ISSUE TITLE
Negative hex values. Is there a fix?

### ISSUE THREAD

**Issue by farmdve** [capstone-engine/capstone#585] opened 2016-02-02 09:15 UTC
So I am using Capstone to disassemble an instruction, but instead I get the following disassembly

`shrd edx, ecx, -0x5e` for opcodes `0FACCA A2` which is actually `shrd edx,ecx,0A2` as disassembled in Ollydbg 2.01.

Any fix for this? There are no explicit negative hex values in computing afaik. You have a sign bit which is bit 31, if you interpret a number as a signed decimal, but in hex the value is always 0-FFFFFFFF. I am not even sure how -0x5e is to be interpreted. 

Ollydbg 2.01 also has a similar bug with negative hex, but it doesnt happen as often.

**Comment by aquynh** [comment] 2016-02-02 09:18
Is this for master branch? can you try with the "next" branch?

**Comment by McLovi9** [comment] 2016-02-22 18:12
I run into the same issue today, only it was when disassembling ARM code.

00D00134    FB04A0E3    mov r0, #-0x5000000
00D00138    10FF2FE1    bx r0

it's hard to see where this code will branch. I check with "next" branch and it's the same negative hex.

Disassembly from IDA pro:

00D00134    FB04A0E3    mov r0, 0x#FB000000
00D00138    10FF2FE1    bx r0

**Comment by aquynh** [comment] 2016-02-23 11:53
you want a positive immediate rather than negative one. this is not hard to fix, but then the question is: when do you want this, and when you dont want?

**Comment by farmdve** [comment] 2016-02-23 14:49
I think it should be an option. This way the user can display it both ways.

**Comment by McLovi9** [comment] 2016-02-23 18:27
IMHO negative value are less desirable, please keep is simple. I prefer unsigned value it makes it (sometimes) easier to spot instructions in hex-view window since opcode immediate value is the same, regardless if its negative.

**Comment by aquynh** [comment] 2016-02-25 00:46
for MOV, i can turn all numbers to positive form. any objection?

**Comment by radare** [comment] 2016-02-25 08:32
What about making it optional?

On Thursday, February 25, 2016 1:46:50 AM CET, Nguyen Anh Quynh 
<notifications@github.com> wrote:
> for MOV, i can turn all numbers to positive form. any objection?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/aquynh/capstone/issues/585#issuecomment-188537433


-- 
Sent using Dekko from my Ubuntu device

**Comment by aquynh** [comment] 2016-02-25 12:32
so how about a new option (named *CS_OPT_POSITIVE* ?)to print **all** immediates in positive form?

**Comment by McLovi9** [comment] 2016-02-25 20:42
sounds good. I just wonder when do you find negative immediate useful ?

**Comment by aquynh** [comment] 2016-02-26 00:05
i think it is useful in some cases, such as "add eax, -1". this is rare, that is why i feel we can switch to positive form in all the cases, and avoid adding a new option.

@radare, do you ever use negative immediate in r2? or you always use positive form?

**Comment by radare** [comment] 2016-02-26 10:06
In my case, i will let users decide if the numbers in a specific instruction are signed or not, as long as this information is kept by r2. I find having negative numbers useful sometimes, but there are other situations where negative numbers are not really meaningful in the context of use. i think it’s hard to decide for one or another behaviour because it depends a lot on the arch and generated code. So i prefer to have this behaviour optional.

for example. the `add eax, -1` makes sense. but not if you go for `and eax, -1`. arithmetic ops are fine with signed immediates, but binary ops does not..

**Comment by aquynh** [comment] 2016-02-26 13:09
ok i will add a new option for this. let me know if you find a better option name than CS_OPT_POSITIVE.

**Comment by radare** [comment] 2016-02-26 13:12
CS_OPT_UNSIGNED

**Comment by McLovi9** [comment] 2016-02-26 21:23
@radare but capstone user will not be able to decide if the number in a specific instruction is signed or not, because it does not keep this information like r2. capstone user will have hard coded predefined list of instructions right ?

I think having unsigned form in all the cases without adding new option is better. Allowing sign or unsigned makes sense only when the disassembler is interactive like e.g. IDA pro and the user can decide on his preference if he wants

add eax, 0x7755EDCB   or
add eax, -0x88AA1235

at the desired address but capstone is just disassembly framework, core for interactive disassembler.

That's said I will be grateful for any solution with CS_OPT_UNSIGNED or without it.

**Comment by aquynh** [comment] 2016-03-14 05:56
i just pushed a commit to the "next" branch to add new option `CS_OPT_UNSIGNED`. by default, this option is disable. turn it on after cs_open() with code like this:

    cs_option(csh, CS_OPT_UNSIGNED, CS_OPT_ON);

for Python, do this with:

    md.imm_unsigned = True

this option only supports ARM for now. other archs are easy, but X86 is tricky because this depends on operand size. the problem is if "detail" option is off, we dont have this info.

if you find any issues, please report.

**Comment by kabeor** [comment] 2021-12-02 09:33
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-02 09:33 UTC
