### ISSUE TITLE
'subtracted' flag is set incorrectly

### ISSUE THREAD

**Issue by vnd** [capstone-engine/capstone#695] opened 2016-06-07 13:24 UTC
0xe1f200b2 (ldrh    r0, [r2, #2]! in ARMv7) is decoded as:

```
Insn {
    address: 1614951176,
    size: 4,
    mnemonic: Some(
        "ldrh"
    ),
    op_str: Some(
        "r0, [r2, #2]!"
    )
}
ARMDetail {
    usermode: false,
    vector_size: 0,
    vector_data: 0,
    cps_mode: ARM_CPSMODE_INVALID,
    cps_flag: ARM_CPSFLAG_INVALID,
    cc: ARM_CC_AL,
    update_flags: false,
    writeback: true,
    mem_barrier: 0,
    op_count: 2,
    operands: [
        ARMOp {
            vector_index: -1,
            shift_type: 0,
            shift_value: 0,
            ty: ARM_OP_REG,
            data: [
                66,
                0
            ],
            subtracted: false
        },
        ARMOp {
            vector_index: -1,
            shift_type: 0,
            shift_value: 0,
            ty: ARM_OP_MEM,
            data: [
                68,
                8589934593
            ],
            **subtracted: true**
        }
    ]
}
```

Data of the second operand is:

```
Mem(
    ARMOpMem {
        base: 68,
        index: 0,
        scale: 1,
        disp: 2
    }
)
```

(the above is an output from Rust wrapper around capstone but I've checked it via plain C program as well)

'subtracted' for the second operands seems to be set incorrectly.

**Comment by vnd** [comment] 2016-06-08 08:45
Also happens for strh (0xe1e530b2).

**Comment by vnd** [comment] 2016-06-08 11:13
Actually it looks like for strh and ldrh 'subtracted' flag should be flipped, e.g. subtracted := !subtracted. I haven't checked the code, but it seems to be always wrong for those two in my case.

**Comment by aquynh** [comment] 2016-06-18 11:48
your code is not properly formatted. you can either put them inside triple "`" (without quote), or paste them to gist.github.com, and put a link to it here.

for the record, can you post your C program reproducing this as well?

**Comment by vnd** [comment] 2016-06-18 12:04
Fixed formatting, here's also a code of C program https://gist.github.com/vnd/76ba4d470c49fb6ed8b962bf54300e3c and it's output:
```
$ ./decode 0xe1e530b2
e1e530b2
0x0:    strh            r3, [r5, #2]!   209
subtracted for op 0: 0
subtracted for op 1: 1
subtracted for op 2: 0
        This instruction belongs to groups: 147 
```
```
$ ./decode 0xe1f200b2
e1f200b2
0x0:    ldrh            r0, [r2, #2]!   66
subtracted for op 0: 0
subtracted for op 1: 1
subtracted for op 2: 0
        This instruction belongs to groups: 147 
```

**Comment by mossberg** [comment] 2017-04-14 00:18
+1

**Comment by kabeor** [comment] 2021-12-07 11:29
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Closed by kabeor** 2021-12-07 11:29 UTC
