### ISSUE TITLE
16bit segment bounds error

### ISSUE THREAD

**Issue by XVilka** [capstone-engine/capstone#111] opened 2014-05-10 01:34 UTC
Using this test from radare2 capstone returns wrong result:

NAME="16bit segment bounds - capstone"
FILE=malloc://1024k
CMDS='
e asm.arch=x86.cs
e asm.bits=16
e anal.hasnext=0
wx e9c300 @ f000:ffaa
s f000:ffaa
pi 1
'
EXPECT='jmp 0xf0070
'
run_test

**Comment by aquynh** [comment] 2015-05-06 02:33
looking back at this, i dont really get why you expect `jmp 0xf0070` at the output. in 16bit mode, the NEAR jump/call instructions are bounded in the same segment. but at the same time, as pointed out by @Notepad in https://github.com/aquynh/capstone/issues/352, `f000:ffaa` is also interpreted as `fff0:00aa`, but in the second case, there is no bound.

this is confused to me, as the Intel manual does not seem to document how target address should be bounded in this case.

**Comment by aquynh** [comment] 2015-05-06 06:52
given that the instruction address is at `f000:ffaa`, the JMP wraps the target address in the same code segment, so the target will be `f000:0070`, correct?

**Comment by XVilka** [comment] 2015-05-06 06:54
@aquynh yes

**Comment by aquynh** [comment] 2015-05-06 06:57
i am wondering how all the other disassemblers deal with this situation, given they only know the absolute starting address, but not code segment address?

how does Radare solve this problem??

**Comment by aquynh** [comment] 2015-05-06 07:08
now i am thinking the solution for this problem is to let the engine know the code segment address, then it can calculate the offset address properly.

the only way to tell Capstone the code segment address is via a new option for *cs_option()* API. thoughts?

**Comment by hlide** [comment] 2015-05-06 08:54
Be aware that setting a code segment may differ when being under 8086 real mode or 286 protected mode.

**Comment by Nodepad** [comment] 2015-05-06 09:00
AFAIK, right now Radare doesn't support segment and segment analysis at all, it just strip upper byte of address to segment (like 0x12345 -> 1000:2345). So in case of Radare with checking of segment bounds it will producing wrong jmps and calls.
It will be awesome to have mechanism for assuming segment register like in IDA or Sourcer. For example, you're assuming what current CS register is 0xFF00, so you treat all code like it executes in this segment. Or you're assuming that DS register is 0xCC00, so you treat all DS-based memory operations like addressing of FF00:xxxx.

**Comment by hlide** [comment] 2015-05-06 09:01
In the case of 16-bit jump/call should the target address be computed this way:

```target address = (jump/call address + byte size of jump/call + target offset) & 65535```

Remember, 16-bit jmp/call are dealing with IP, neither EIP nor RIP so the computation are done with 16-bit word.

**Comment by hlide** [comment] 2015-05-06 09:19
I have just realized that you need a base address to make a correct 16-bit wrapping because you seem to deal with an absolute address even in 16-bit. In real mode, you kind need it. In 16-bit protected mode, you only have selector index and unless you have a way to get their base addresses, you are stuck with relative address. So yes, having a new option for cs_option() API to set those segments is probably the only solution - at least for the real mode.

**Comment by hlide** [comment] 2015-05-06 09:52
@Notepad "Or you're assuming that DS register is 0xCC00, so you treat all DS-based memory operations like addressing of FF00:xxxx." I guess you mean `CC00:xxxx`.

**Comment by Nodepad** [comment] 2015-05-06 10:01
@hlide Oh, yes, you're right, fixed. Thanks.

**Comment by XVilka** [comment] 2015-05-06 11:22
@aquynh yep, I think cs_option() is the right approach, lets ask @radare though.

**Comment by aquynh** [comment] 2015-05-07 07:23
@Nodepad, why is it "awesome" to assume segment registers, which maybe very much wrong? isn't it much better to let program tell the disassembler the segment value to be sure?

anybody know exactly how Udis86 & Distorm cope with this 16bit target addresses in this problem?

**Comment by Nodepad** [comment] 2015-05-07 07:57
@aquynh I'm not sure where should it be in disassembler or in program. But this is very good thing for analysis of code with real addressing. AFAIK, it's disassembler who computes addresses for code and data, maybe I'm wrong.

**Comment by hlide** [comment] 2015-05-07 08:52
@aquynh I think you miss the point: I don't think udis86 and distorm are designed to disassemble code in 16-bit real mode so they probably don't handle this correctly. I'm not expecting for recent disassemblers to work with 16-bit real mode properly as there is no big interest in it nowadays.  

udis86:
```
uint64_t
ud_syn_rel_target(struct ud *u, struct ud_operand *opr)
{
  const uint64_t trunc_mask = 0xffffffffffffffffull >> (64 - u->opr_mode);
  switch (opr->size) {
  case 8 : return (u->pc + opr->lval.sbyte)  & trunc_mask;
  case 16: return (u->pc + opr->lval.sword)  & trunc_mask;
  case 32: return (u->pc + opr->lval.sdword) & trunc_mask;
  default: UD_ASSERT(!"invalid relative offset size.");
    return 0ull;
  }
}
```

distorm:
```
case O_PC:
#ifdef SUPPORT_64BIT_OFFSET
    str_off64(str, (di->imm.sqword + di->addr + di->size) & addrMask);
#else
    str_code_hdw(str, ((_OffsetType)di->imm.sdword + di->addr + di->size) & (uint32_t)addrMask);
#endif
```

**Comment by hlide** [comment] 2015-05-07 12:30
if you don't want to add a code segment in the context, here is a solution:

* 16-bit mode in real/protected mode not using a flat model: set the 64-bit address as a pair of 32-bit words, the most significant of which is a segment/selector value and the least significant of which is the 16-bit relative offset. Computation of target address will only touch the least significant 32-bit of this address and when displaying the operand, it should be truncated to a 16-bit word.

* 32-bit mode in real/protected mode not using a flat model: set the 64-bit address as a pair of 32-bit words, the most significant of which is a segment/selector value and the least significant of which is the 32-bit relative offset. Computation of target address will only touch the least significant 32-bit of this address and when displaying the operand, it should be truncated to a 32-bit word.

* 64-bit mode in real/protected mode not using a flat model: totally irrelevant and impossible.

in segment model:
```
target address = (pc & 0xFFFFFFFF00000000) | ((pc + imm) & address mask);
```

in flat model:
```
target address = ((pc + imm) & address mask);
```

where *pc* is the address of the following instruction, *imm* an immediate value sign-extended from a 8/16-bit word in 16-bit mode or a 8/32-bit word in 32-bit mode and *address mask* a value to truncate the offset part into a valid 16-bit word when in 16-bit mode and into a valid 32-bit word when in 32-bit mode.

So if turning segment model on, your 16-bit mode example will give:

```
address    | code                             | mnemonic
0000F:FFAA | E9C300.......................... | jmp  0xF:0x70
```

in flat model (default), it would give (wrong result because *address* should be contained in a 16-bit word to work properly) :
```
address   | code                             | mnemonic
F0000FFAA | E9C300.......................... | JMP  0x70
```

Indeed, you could consider segment model by default for 16-bit mode, and flat model (the actual way capstone does) for 32-bit and 64-bit modes. You can add an option to set the memory model if needed.

**Comment by radare** [comment] 2015-05-14 08:15
![x86-16](https://cloud.githubusercontent.com/assets/917142/7628316/2139e116-fa22-11e4-9ba6-376bcb1ff493.png)

**Comment by aquynh** [comment] 2015-05-14 09:14
no need to post this screenshot, as this is known, and exactly what we are discussing here: to find the solution to handle 16bit code with short/near JMP/CALL. 

so with all people said here, what is your solution?

**Comment by hlide** [comment] 2015-05-14 10:46
Small correction for segment model:
```target address = (address & 0xFFFFFFFF00000000) | ((pc + imm) & address mask);```
where *address* is the address of the branching instruction. It is important because segment part should be kept the same when *pc* is overflowing in 32-bit.

**Comment by aquynh** [comment] 2015-06-06 08:35
the proposal of @hlide still assumes the segment value for 16bit mode, so the problem is not totally solved.

towards the final solution, i will add a new option for `cs_option()` to define the segment value for X86 16bit mode. let me know if you have any concerns, thanks.

**Comment by hlide** [comment] 2015-06-07 00:23
@aquynh what do you mean by "still assumes the segment value for 16bit mode."?

**Comment by aquynh** [comment] 2015-06-07 12:13
i mean the segment value is still defined by the engine, but not by user, and cannot be customized by user.

**Comment by radare** [comment] 2015-08-13 18:22
Here's a oneliner to test this with rasm2:
```
$ rasm2 -o 0xfffaa -a x86 -b 16 -d e9c300
jmp 0xf0070
```

The patch I wrote for radare2 is the following, do you still think a mode option is needed to specify a separate segment? memory in x86-16 is linear, even segmented, segments overlap so the memory can be considered flat under the hood.

Feel free to review/adapt/import this patch:

https://github.com/radare/radare2/blob/master/shlr/capstone-patches/fix-x86-16.patch

**Comment by XVilka** [comment] 2015-09-02 16:18
Yep, I think patch from @radare is good enough.

**Comment by Maijin** [comment] 2015-09-22 15:04
ping ?

**Comment by radare** [comment] 2015-09-22 15:32
he’s waiting for my answer on some questions, the thing is that all i know about code segments is in real mode, i never tried in protected mode (286), and i dont think the 286 mode is used anywhere nowadays.

In real mode, the segment just extends the real physical address, and this makes it possible to have two different segment addresses pointing to the same physical address. thats why my patch works. not by luck. just because that’s how segments work internally to select a specific ram region.

In protected and 286 mode segments are used differently, and this is probably not related to this issue. Because non-cs segments are usually used to specify access to an isolated memory in protected 286 and 386 modes. But thats not the case for 8086 real mode.

Also, this jump instruction doesnt specifies the segment, so it implies the code segment, so the whole discussion makes no point imho, because the current disasm jumps to a wrong address, and this instruction is extracted from a real use case (found in various BIOS and UEFIs)

I see more benefits in having a patch that works in 90% of use cases, than keeping this thing broken for 90% of the x86-16 jumps.

For more info

https://en.wikipedia.org/wiki/X86_memory_segmentation <https://en.wikipedia.org/wiki/X86_memory_segmentation>

Having a more complete segment addressing will result in something more formal and correct, because my current approach just changes CS in order to get the correct physical address, so, two different jumps can result into the same destination, but again, this instruction (e9c300) is just a relative jump, without specifying any segment.

**Comment by Nodepad** [comment] 2015-09-23 13:08
@radare What problem in creating patch for 100% of use cases?

**Comment by radare** [comment] 2015-09-23 14:58
the problem of a full featured patch is mainly that it will require extra/changing apis, redesign, and probably the most important one: time. 

I’m already shipping this patch with r2 version of capstone, so r2 users are “safe” unless they compile against packaged version of capstone. The current issue is found and reported by different users already, and its verfiied in the r2 regression testsuite.

The other cases we are discussing here havent been reported by anyone yet. So i would like to have this workaround until a proper fix comes.

**Comment by XVilka** [comment] 2016-03-06 11:03
Hello there! Small update - we all completely forgot about rare, still used 16bit protected mode. https://github.com/radare/radare2/issues/4196
Currently capstone assumes real mode addressing mode in case of 16bit.

**Comment by hlide** [comment] 2016-03-06 11:24
nope it wasn't forgot, I already addressed this issue with a solution above. But I don't know what has been implemented since.

**Comment by XVilka** [comment] 2016-03-06 11:30
@hlide yes, sorry, missed your comment.

**Comment by radare** [comment] 2016-03-06 12:39
So, do you agree that capstone needs a config option to select the memory model used to properly disassemble code?

**Comment by hlide** [comment] 2016-03-06 13:14
yes it lacks an option to tell the memory model (flat or segmented)

**Comment by Maijin** [comment] 2016-04-07 22:10
Soooo ?

**Comment by aquynh** [comment] 2016-04-08 02:17
how about having somebody from Radare community worked on this then send in a PR? thanks.

**Comment by Fighter19** [comment] 2020-05-23 22:12
I'm a bit curious, has such cs_option been implemented already?
I would like to be able to manually specify the base address for the corresponding segment.

**Comment by kabeor** [comment] 2021-12-01 11:01
Close this issue for now because of legacy, plz feel free to open a new issue if there is progress.
thx :)

**Closed by kabeor** 2021-12-01 11:01 UTC
Labels: bug

**Comment by XVilka** [comment] 2023-07-13 03:59
It it still a valid issue and wasn't fixed
